#############################################
# Maria DB server + backup
#############################################
# version: "3.4"

services:

  db:
    image: mariadb:latest
    container_name: db-01
    volumes:
    # create persistent docker volume
    - /mnt/data/Project/Kian/Kian-Project/reminder/mariadb/data:/var/lib/mysql
    # mount configuration
    - /mnt/data/Project/Kian/Kian-Project/reminder/mariadb/config/:/etc/mysql/conf.d
    restart: always
    environment:
    - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
    ports:
    - "3306:3306"

